# Generated by Django 3.1 on 2020-08-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200823_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
