# Generated by Django 3.1 on 2020-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_group_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_completed_index',
            field=models.IntegerField(default=0),
        ),
    ]
