# Generated by Django 3.1 on 2020-08-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200824_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.TextField(default=None, null=True),
        ),
    ]
