# Generated by Django 3.1 on 2020-08-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='selected_group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.group'),
        ),
    ]
