# Generated by Django 3.1 on 2020-08-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200828_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprogress',
            name='last_modified',
        ),
    ]
