# Generated by Django 3.1 on 2020-09-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_groupprogress_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='icon_color',
            field=models.TextField(default=None, null=True),
        ),
    ]
